version: "3.8"
services:
  nodejs-server:
    build:
      context: .
      dockerfile: Dockerfile-nodejs-server
    ports:
      - 8030:80

  chat-server-swift:
    build:
      context: .
      dockerfile: Dockerfile-ChatServerSwift
    environment:
      PORT: 80
    ports:
      - 8031:80
