version: "3.8"
services:
  nodejs-server:
    build:
      context: .
      dockerfile: Dockerfile-nodejs-server
    ports:
      - 8030:80

  swift-server:
    build:
      context: .
      dockerfile: Dockerfile-swift-server
    ports:
      - 8031:80
